### ISSUE TITLE
vue-markdown error

### ISSUE THREAD

**Issue by moringaman** [moringaman/cadence-desktop#20]
```
Uncaught Error: Cannot find module 'babel-runtime/core-js/get-iterator'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/tmp/.mount_cadenc5my5FO/app/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at webpackUniversalModuleDefinition (/tmp/.mount_cadenc5my5FO/app/resources/app.asar/node_modules/vue-markdown/dist/vue-markdown.common.js:9:28)
    at Object.<anonymous> (/tmp/.mount_cadenc5my5FO/app/resources/app.asar/node_modules/vue-markdown/dist/vue-markdown.common.js:16:3)
    at Object.<anonymous> (/tmp/.mount_cadenc5my5FO/app/resources/app.asar/node_modules/vue-markdown/dist/vue-markdown.common.js:463:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
```

**Comment by moringaman** [comment]
Fixed this by updating babel-core which is now @ "babel-core": "^6.26.3"
